"""Auto-generated by mpl_animator.py from examples/lissajous_3d_static.py
   a sweeps 1 -> 6 over 80 frames @ 20fps
"""
import numpy as np
import matplotlib; matplotlib.use('Agg')
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
b  = 2.0
c  = 1.0
delta = np.pi / 4
t = np.linspace(0, 2 * np.pi, 1000)
y = np.sin(b * t)
z = np.sin(c * t)
colors = plt.cm.plasma(np.linspace(0, 1, len(t)))
fig = plt.figure(figsize=(8, 6))
ax  = fig.add_subplot(111, projection='3d')
import matplotlib.animation as animation
import multiprocessing, os, tempfile, shutil, time
from PIL import Image

# -- frame update ----------------------------------------------------
def update(_frame):
    a = 1 + _frame * 0.0625
    x = np.sin(a * t + delta)
    fig.clear()
    fig = plt.figure(figsize=(8, 6))
    ax.scatter(x, y, z, c=colors, s=2, alpha=0.8)
    ax.set_title(f"3D Lissajous  a={a:.1f}, b={b:.1f}, c={c:.1f}")
    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.set_zlabel("Z")
    ax.set_xlim(-1, 1)
    ax.set_ylim(-1, 1)
    ax.set_zlim(-1, 1)
    plt.tight_layout()

# -- sequential (FuncAnimation) --------------------------------------
def render_sequential():
    ani = animation.FuncAnimation(
        fig, update, frames=80, interval=50, blit=False)
    ani.save("lissajous_3d_static_animated.gif", writer="pillow", fps=20)
    print("  Saved ->", "lissajous_3d_static_animated.gif")

# -- parallel worker (one PNG per frame) -----------------------------
def _render_one(job):
    _frame, _tmpdir = job
    import numpy as np
    import matplotlib; matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    from mpl_toolkits.mplot3d import Axes3D
    b  = 2.0
    c  = 1.0
    delta = np.pi / 4
    t = np.linspace(0, 2 * np.pi, 1000)
    y = np.sin(b * t)
    z = np.sin(c * t)
    colors = plt.cm.plasma(np.linspace(0, 1, len(t)))
    fig = plt.figure(figsize=(8, 6))
    ax  = fig.add_subplot(111, projection='3d')
    a = 1 + _frame * 0.0625
    x = np.sin(a * t + delta)
    ax.scatter(x, y, z, c=colors, s=2, alpha=0.8)
    ax.set_title(f"3D Lissajous  a={a:.1f}, b={b:.1f}, c={c:.1f}")
    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.set_zlabel("Z")
    ax.set_xlim(-1, 1)
    ax.set_ylim(-1, 1)
    ax.set_zlim(-1, 1)
    plt.tight_layout()
    _path = os.path.join(_tmpdir, f"frame_{_frame:05d}.png")
    plt.savefig(_path, dpi=100, bbox_inches="tight")
    plt.close("all")
    return _path

def render_parallel(n_workers):
    tmpdir = tempfile.mkdtemp(prefix="anim_")
    chunk  = max(1, 80 // (n_workers * 4))
    print(f"  Rendering 80 frames on {n_workers} workers...")
    try:
        jobs  = [(_i, tmpdir) for _i in range(80)]
        with multiprocessing.Pool(n_workers) as pool:
            paths = list(pool.imap(_render_one, jobs, chunksize=chunk))
        paths.sort()
        print(f"  Stitching {len(paths)} frames...")
        imgs = [Image.open(q).convert("RGBA") for q in paths]
        imgs[0].save("lissajous_3d_static_animated.gif", save_all=True, append_images=imgs[1:],
                     loop=0, duration=50, optimize=False)
        print("  Saved ->", "lissajous_3d_static_animated.gif")
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)

# -- main ------------------------------------------------------------
if __name__ == "__main__":
    import sys
    n_workers = 0 or multiprocessing.cpu_count()
    t0 = time.perf_counter()
    if "--sequential" in sys.argv:
        print("Sequential mode...")
        render_sequential()
    else:
        print(f"Parallel mode ({n_workers} workers)...")
        try:
            render_parallel(n_workers)
        except Exception as err:
            print(f"  Parallel failed ({err}), falling back to sequential...")
            render_sequential()
    print(f"  Total: {time.perf_counter()-t0:.1f}s")
