"""Auto-generated by mpl_animator.py from examples/wave_static.py
   f sweeps 3 -> 60 over 10 frames @ 20fps
"""
import numpy as np
import matplotlib; matplotlib.use('Agg')
import matplotlib.pyplot as plt
t   = np.linspace(0, 1, 1000)
freqs    = np.fft.rfftfreq(len(t), d=t[1]-t[0])
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(9, 6))
import matplotlib.animation as animation
import multiprocessing, os, tempfile, shutil, time
from PIL import Image

# -- frame update ----------------------------------------------------
def update(_frame):
    f = 3 + _frame * 5.7
    y   = np.sin(2*np.pi*f*t) + 0.4*np.sin(2*np.pi*2*f*t)
    spectrum = np.abs(np.fft.rfft(y))
    _axs = list(ax1) if hasattr(ax1,'__iter__') else [ax1]
    [_a.clear() for _a in _axs]
    _axs = list(ax2) if hasattr(ax2,'__iter__') else [ax2]
    [_a.clear() for _a in _axs]
    fig.tight_layout(pad=3)
    ax1.plot(t, y, 'royalblue', lw=1.5)
    ax1.set_xlim(0, 1)
    ax1.set_ylim(-2.2, 2.2)
    ax1.set_xlabel("Time (s)")
    ax1.set_ylabel("Amplitude")
    ax1.set_title(f"Signal  f = {f:.1f} Hz")
    ax1.grid(True, alpha=0.3)
    ax2.plot(freqs, spectrum, 'tomato', lw=1.5)
    ax2.set_xlim(0, 150)
    ax2.set_ylim(0, 600)
    ax2.set_xlabel("Frequency (Hz)")
    ax2.set_ylabel("|FFT|")
    ax2.set_title("Frequency Spectrum")
    ax2.grid(True, alpha=0.3)

# -- sequential (FuncAnimation) --------------------------------------
def render_sequential():
    ani = animation.FuncAnimation(
        fig, update, frames=10, interval=50, blit=False)
    ani.save("wave_static_animated.gif", writer="pillow", fps=20)
    print("  Saved ->", "wave_static_animated.gif")

# -- parallel worker (one PNG per frame) -----------------------------
def _render_one(job):
    _frame, _tmpdir = job
    import numpy as np
    import matplotlib; matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    t   = np.linspace(0, 1, 1000)
    freqs    = np.fft.rfftfreq(len(t), d=t[1]-t[0])
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(9, 6))
    f = 3 + _frame * 5.7
    y   = np.sin(2*np.pi*f*t) + 0.4*np.sin(2*np.pi*2*f*t)
    spectrum = np.abs(np.fft.rfft(y))
    fig.tight_layout(pad=3)
    ax1.plot(t, y, 'royalblue', lw=1.5)
    ax1.set_xlim(0, 1)
    ax1.set_ylim(-2.2, 2.2)
    ax1.set_xlabel("Time (s)")
    ax1.set_ylabel("Amplitude")
    ax1.set_title(f"Signal  f = {f:.1f} Hz")
    ax1.grid(True, alpha=0.3)
    ax2.plot(freqs, spectrum, 'tomato', lw=1.5)
    ax2.set_xlim(0, 150)
    ax2.set_ylim(0, 600)
    ax2.set_xlabel("Frequency (Hz)")
    ax2.set_ylabel("|FFT|")
    ax2.set_title("Frequency Spectrum")
    ax2.grid(True, alpha=0.3)
    _path = os.path.join(_tmpdir, f"frame_{_frame:05d}.png")
    plt.savefig(_path, dpi=100, bbox_inches="tight")
    plt.close("all")
    return _path

def render_parallel(n_workers):
    tmpdir = tempfile.mkdtemp(prefix="anim_")
    chunk  = max(1, 10 // (n_workers * 4))
    print(f"  Rendering 10 frames on {n_workers} workers...")
    try:
        jobs  = [(_i, tmpdir) for _i in range(10)]
        with multiprocessing.Pool(n_workers) as pool:
            paths = list(pool.imap(_render_one, jobs, chunksize=chunk))
        paths.sort()
        print(f"  Stitching {len(paths)} frames...")
        imgs = [Image.open(q).convert("RGBA") for q in paths]
        imgs[0].save("wave_static_animated.gif", save_all=True, append_images=imgs[1:],
                     loop=0, duration=50, optimize=False)
        print("  Saved ->", "wave_static_animated.gif")
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)

# -- main ------------------------------------------------------------
if __name__ == "__main__":
    import sys
    n_workers = 0 or multiprocessing.cpu_count()
    t0 = time.perf_counter()
    if "--sequential" in sys.argv:
        print("Sequential mode...")
        render_sequential()
    else:
        print(f"Parallel mode ({n_workers} workers)...")
        try:
            render_parallel(n_workers)
        except Exception as err:
            print(f"  Parallel failed ({err}), falling back to sequential...")
            render_sequential()
    print(f"  Total: {time.perf_counter()-t0:.1f}s")
